
// 模块级变量存储URL参数
let moduleUrlParams = {};

// 血压监测应用配置文件
const CONFIG = {

    // 文本配置 - 所有显示的文本内容
    text: {
        title: "血压监测报告",  // 页面标题
        comparisonTitle: "Comparison with your 7-day average",  // 7天对比标题
        systolicComparisonLabel: "Systolic",  // 收缩压对比标签
        diastolicComparisonLabel: "Diastolic",  // 舒张压对比标签
        aiAnalysisLabel: "Analysis generated by AI",  // AI分析标签
        betaBadge: "beta",  // Beta标识
        loadingText: "loading...",  // 加载中文本
        errorMissingParams: "Missing required parameters",  // 缺少参数错误
        errorLoadFailed: "Failed to load data, please try again later",  // 数据加载失败错误
        errorNetwork: "Network error",  // 网络错误
    },

    // 图片配置 - 所有使用的图片路径
    images: {
        systolicUpArrow: "./icon_up.png",  // 收缩压上升箭头
        systolicDownArrow: "./icon_down.png",  // 收缩压下降箭头
        diastolicUpArrow: "./icon_up.png",  // 舒张压上升箭头
        diastolicDownArrow: "./icon_down.png",  // 舒张压下降箭头
        playIcon: "./icon_play.png",  // 播放图标
        stopIcon: "./icon_stop.png",  // 停止图标
        stableIcon: "./icon_stable.png"
    },

    // 默认数据 - 用于测试或初始显示
    defaultData: {
        blood_pressure_data: {
            measurement_time: "",  // 默认日期
            high_pressure: 0,  // 默认收缩压
            low_pressure: 0,  // 默认舒张压
            heart_rate: 0  // 默认心率
        },
        incentive_data: {
            AvgHigh: 0,  // 默认收缩压差值
            AvgLow: 0,  // 默认舒张压差值
            VoiceText: "",  // 默认AI分析文本
            bpLevel: 0  // 默认血压等级：1=正常，2=偏高，3=高血压1期，4=高血压2期
        }
    }
};

// 获取URL参数函数
function getUrlParams() {
    const urlParams = new URLSearchParams(window.location.search);
    return {
        token: urlParams.get('token'),  // 用户认证token
        phoneDataId: urlParams.get('phoneDataId'),  // 手机数据ID
        un: urlParams.get('un'),  // 用户名
        baseUrl: urlParams.get('baseUrl'),  // 基础URL
        timeFormat: urlParams.get('timeFormat'),  // 时间格式参数
        bpUnit: urlParams.get('bpUnit')  // 血压单位参数
    };
}

// 更新文本内容函数
function updateTextContent(elementId, text) {
    const element = document.getElementById(elementId);
    if (element) {
        element.textContent = text;  // 设置元素文本内容
    }
}

// 更新图片源函数
function updateImageSource(elementId, src, alt = '') {
    const element = document.getElementById(elementId);
    if (element) {
        element.src = src;  // 设置图片源
        if (alt) element.alt = alt;  // 设置可选的alt文本
    }
}
function updateAiText(text) {
    const el = document.getElementById('aiAnalysisText');
    if (el) {
        el.textContent = text;
        const spacer = document.createElement('span');
        spacer.className = 'last-line-spacer';
        el.appendChild(spacer);
    }
}

// 更新页面数据函数
function updatePageData(data) {
    const { timeFormat, bpUnit } = moduleUrlParams;
    updateAiText(data.incentive_data.VoiceText);  // 更新AI分析文本
    // 更新箭头图片
    var systolicArrowSrc = CONFIG.images.stableIcon
    const hight = data.blood_pressure_data.high_pressure - data.incentive_data.AvgHigh
    if (hight > 0) {
        systolicArrowSrc = CONFIG.images.systolicUpArrow
    } else if (hight < 0) {
        systolicArrowSrc = CONFIG.images.systolicDownArrow
    } else {
        systolicArrowSrc = CONFIG.images.stableIcon
    }
    var diastolicArrowSrc = CONFIG.images.stableIcon
    const low = data.blood_pressure_data.low_pressure - data.incentive_data.AvgLow
    if (low > 0) {
        diastolicArrowSrc = CONFIG.images.systolicUpArrow
    } else if (low < 0) {
        diastolicArrowSrc = CONFIG.images.systolicDownArrow
    } else {
        diastolicArrowSrc = CONFIG.images.stableIcon
    }
    // 根据差值设置颜色：高值红色，低值绿色
    const systolicColor = hight > 0 ? 'rgba(235, 70, 82, 1)' : (hight < 0 ? 'rgba(46, 209, 55, 1)' : '');
    const diastolicColor = low > 0 ? 'rgba(235, 70, 82, 1)' : (low < 0 ? 'rgba(46, 209, 55, 1)' : '');

    updateTextContentWithColor('systolicDiff', hight == 0 ? '' : Math.abs(bpUnit === 'mmHg' ? hight : mmhgToKpa(hight)), systolicColor);  // 更新收缩压差值和颜色
    updateTextContentWithColor('diastolicDiff', low == 0 ? '' : Math.abs(bpUnit === 'mmHg' ? low : mmhgToKpa(low)), diastolicColor);  // 更新舒张压差值和颜色
    updateImageSource('systolicArrow', systolicArrowSrc, "");
    updateImageSource('diastolicArrow', diastolicArrowSrc, "");
}
// 更新文本内容和颜色函数
function updateTextContentWithColor(elementId, text, color) {
    const element = document.getElementById(elementId);
    if (element) {
        element.textContent = text;  // 设置元素文本内容
        element.style.color = color;   // 设置文本颜色
    }
}

function mmhgToKpa(mmhg) {
    const f = mmhg / 7.5;
    // 使用 toFixed(1) 实现四舍五入保留一位小数
    return parseFloat(f.toFixed(1));
}
// 创建主要内容HTML函数
function createMainContent(data) {
    console.log('创建主要内容，数据:', data);
    return `
    <div class="title">AI Analysis</div>
        <!-- 7天提示 -->
        <div class="comparison-title" id="comparisonTitle">${CONFIG.text.comparisonTitle}</div>
        <div class="comparison-values">
            <div class="comparison-item">
                <div class="comparison-label" id="systolicComparisonLabel">${CONFIG.text.systolicComparisonLabel}</div>
                <img class="comparison-img" id="systolicArrow" src="${data.incentive_data.AvgHigh > 0 ? CONFIG.images.systolicUpArrow : (data.incentive_data.AvgHigh < 0 ? CONFIG.images.systolicDownArrow : CONFIG.images.stableIcon)}" alt="${data.incentive_data.AvgHigh > 0 ? 'Up arrow' : (data.incentive_data.AvgHigh < 0 ? 'Down arrow' : 'Stable')}">
                <div class="avg" id="systolicDiff">${Math.abs(data.incentive_data.AvgHigh)}</div>
            </div>
            <div class="divider-small"></div>
            <div class="comparison-item">
                <div class="comparison-label" id="diastolicComparisonLabel">${CONFIG.text.diastolicComparisonLabel}</div>
                <img class="comparison-img" id="diastolicArrow" src="${data.incentive_data.AvgLow > 0 ? CONFIG.images.diastolicUpArrow : (data.incentive_data.AvgLow < 0 ? CONFIG.images.diastolicDownArrow : CONFIG.images.stableIcon)}" alt="${data.incentive_data.AvgLow > 0 ? 'Up arrow' : (data.incentive_data.AvgLow < 0 ? 'Down arrow' : 'Stable')}">
                <div class="avg" id="diastolicDiff">${Math.abs(data.incentive_data.AvgLow)}</div>
            </div>
        </div>

        <!-- AI分析 -->
        <div class="ai-analysis">
            <div class="ai-text" id="aiAnalysisText">${data.incentive_data.VoiceText}</div>
            <img class="play-icon" id="playIcon" src="${CONFIG.images.playIcon}" alt="Play icon">
        </div>
        
        <!-- beta -->
        <div class="ai-label-container">
            <div class="ai-label" id="aiAnalysisLabel">${CONFIG.text.aiAnalysisLabel}</div>
            <div class="beta-badge" id="betaBadge">${CONFIG.text.betaBadge}</div>
        </div>
    `;
}

// 创建加载中内容函数
function createLoadingContent() {
    return `
        <div class="loading">
            <i class="fas fa-spinner fa-spin"></i> ${CONFIG.text.loadingText}
        </div>
    `;
}
function createSuccessToast(message) {
    const toast = document.createElement('div');
    toast.className = 'toast toast-success';
    toast.innerHTML = `
        <div class="toast-message">${message}</div>
    `;
    return toast;
}
function createErrorToast(message) {
    const toast = document.createElement('div');
    toast.className = 'toast toast-error';
    toast.innerHTML = `
        <div class="toast-message">${message}</div>
    `;
    return toast;
}
function createErrorContent(message) {
    const toast = document.createElement('div');
    toast.className = 'error-message';
    toast.innerHTML = `
        <div class="toast-message">${message}</div>
    `;
    return toast;
}
function showToast(toastElement, duration = 1000) {
    const existingToasts = document.querySelectorAll('.toast');
    existingToasts.forEach(toast => toast.remove());
    document.body.appendChild(toastElement);
    setTimeout(() => {
        toastElement.classList.add('fade-out');
        setTimeout(() => {
            if (toastElement.parentNode) {
                toastElement.parentNode.removeChild(toastElement);
            }
        }, 100);
    }, duration);
}
let currentAudio = null;
let playAnimationInterval = null;
let currentPlayIconIndex = 0;
const playIcons = ['./icon_play.png', './icon_play1.png', './icon_play2.png'];
const stopIcon = './icon_stop.png';

function handlePlay(VoiceUrl) {

    // 如果已经在播放，点击则停止
    if (currentAudio && !currentAudio.paused) {
        stopPlayback();
        return;
    }

    // // 如果已经有音频对象但处于暂停状态，恢复播放
    // if (currentAudio && currentAudio.paused) {
    //     resumePlayback();
    //     return;
    // }

    
    try {
        currentAudio = new Audio(VoiceUrl);
        startPlayAnimation();
        currentAudio.play().then(() => {
            console.log('音频开始播放');
            onPlayStart();
        }).catch(error => {
            console.error('播放失败:', error);
            stopPlayAnimation();
            resetPlayIcon();
            currentAudio = null;
            const toast = createErrorContent(CONFIG.text.errorNetwork);
            showToast(toast);
        });

        currentAudio.addEventListener('ended', () => {
            console.log('音频播放结束');
            stopPlayAnimation();
            resetPlayIcon();
            onPlayEnd();
            currentAudio = null;
        });

        currentAudio.addEventListener('error', (e) => {
            console.error('音频播放错误:', e);
            stopPlayAnimation();
            resetPlayIcon();
            currentAudio = null;
            const toast = createErrorContent(CONFIG.text.errorNetwork);
            showToast(toast);
        });

        return currentAudio;
    } catch (error) {
        console.error('播放异常:', error);
        stopPlayAnimation();
        resetPlayIcon();
        currentAudio = null;
        const toast = createErrorContent(CONFIG.text.errorNetwork);
        showToast(toast);
        return null;
    }
}

// 开始播放动画
function startPlayAnimation() {
    const playButton = document.getElementById('playIcon');
    if (!playButton) return;

    stopPlayAnimation(); // 先清除之前的动画

    currentPlayIconIndex = 0;
    playAnimationInterval = setInterval(() => {
        currentPlayIconIndex = (currentPlayIconIndex + 1) % playIcons.length;
        playButton.src = playIcons[currentPlayIconIndex];
    }, 500); // 每500毫秒切换一次图标
}

// 停止播放动画
function stopPlayAnimation() {
    if (playAnimationInterval) {
        clearInterval(playAnimationInterval);
        playAnimationInterval = null;
    }
}

// 重置播放图标
function resetPlayIcon() {
    const playButton = document.getElementById('playIcon');
    if (playButton) {
        playButton.src = playIcons[0]; // 重置为第一个播放图标
    }
}

// 停止播放函数
function stopPlayback() {
    if (currentAudio) {
        currentAudio.pause();
        currentAudio.currentTime = 0;
        console.log('音频已停止');
        stopPlayAnimation();
        currentAudio = null;
        const playButton = document.getElementById('playIcon');
        if (playButton) {
            playButton.src = stopIcon;
        }
    }
}

// 暂停播放函数
// function pausePlayback() {
//     if (currentAudio && !currentAudio.paused) {
//         currentAudio.pause();
//         console.log('音频已暂停');
//         stopPlayAnimation();
//         // 暂停时显示停止图标
//         const playButton = document.getElementById('playIcon');
//         if (playButton) {
//             playButton.src = stopIcon;
//         }
//     }
// }

// 继续播放函数
function resumePlayback() {
    if (currentAudio && currentAudio.paused) {
        currentAudio.play();
        console.log('音频继续播放');
        startPlayAnimation();
    }
}

// 播放开始回调
function onPlayStart() {
    console.log('播放开始，可以更新UI状态');
    // 比如：显示播放中状态、禁用播放按钮等
}

// 播放结束回调
function onPlayEnd() {
    console.log('播放结束，可以更新UI状态');
    // 比如：显示播放完成状态、启用播放按钮等
}


// 处理播放按钮点击事件
function handlePlayButtonClick(data) {
    return function () {
        const playButton = document.getElementById('playIcon');
        if (!playButton) return;

        

        // 如果正在播放，点击则停止
        if (currentAudio && !currentAudio.paused) {
            stopPlayback();
            playButton.src = stopIcon;
        } else {
            handlePlay(data.incentive_data.VoiceUrl);
        }
    };
}
// 页面卸载时清理资源
window.addEventListener('beforeunload', () => {
    if (currentAudio) {
        stopPlayback();
    }
    if (playAnimationInterval) {
        clearInterval(playAnimationInterval);
    }
});

// 显示反馈区域函数
function showFeedbackContainer() {
    const feedbackContainer = document.getElementById('feedbackContainer');
    console.log('显示反馈区域，容器元素:', feedbackContainer);
    if (feedbackContainer) {
        feedbackContainer.classList.add('show');
        feedbackContainer.style.display = 'block';
        console.log('反馈区域已显示');
    } else {
        console.error('未找到反馈容器元素');
    }
}

// 隐藏反馈区域函数
function hideFeedbackContainer() {
    const feedbackContainer = document.getElementById('feedbackContainer');
    const feedbackTextarea = document.getElementById('feedbackTextarea');
    if (feedbackContainer) {
        feedbackContainer.classList.remove('show');
        feedbackContainer.style.display = 'none';
    }
    // 清空反馈内容
    if (feedbackTextarea) {
        feedbackTextarea.value = '';
    }
}

// 异步处理提交按钮点击
async function handleSubmitButton() {
    const submitButton = document.getElementById('submitButton');
    const feedbackTextarea = document.getElementById('feedbackTextarea');
    const reminderCheckbox = document.getElementById('reminderCheckbox');

    const feedback = feedbackTextarea.value.trim();  // 获取反馈内容并去除首尾空格
    const dontRemind = reminderCheckbox.checked;  // 获取是否7天内不再提醒

    if (!feedback) {
        const errorToast = createErrorContent(CONFIG.text.alertNoFeedback);  // 创建无反馈内容提示
        showToast(errorToast);  // 显示错误toast
        return;
    }

    // 更新按钮状态为提交中
    submitButton.disabled = true;
    submitButton.textContent = CONFIG.text.submittingText;
    setIncentiveFeedback(2, feedback, dontRemind)

}
function handleReminderChange() {
    const reminderCheckbox = document.getElementById('reminderCheckbox');

    if (reminderCheckbox.checked) {
        setIncentiveFeedback(null, null, true)
    } else {
        setIncentiveFeedback(null, null, false)
    }
}
// 绑定事件函数
function bindEvents(data) {
    const playButton = document.getElementById('playIcon');

    // 绑定播放按钮事件
    if (playButton) {
        playButton.addEventListener('click', handlePlayButtonClick(data));
        console.log('播放按钮事件已绑定');
    } else {
        console.error('播放按钮未找到');
    }

}

// 主初始化函数
async function initPage() {
    console.log('初始化页面开始');
    const { token, phoneDataId, un, baseUrl, timeFormat, bpUnit } = getUrlParams();  // 获取URL参数
    // 存储到模块级变量，供其他函数使用
    moduleUrlParams = { token, phoneDataId, un, baseUrl, timeFormat, bpUnit };
    getIncentiveInfo()
}
// 获取激励信息函数
async function getIncentiveInfo() {
    const { baseUrl, token, phoneDataId, un } = moduleUrlParams;

    const mainContent = document.querySelector('.main-content');  // 获取主要内容容器
    mainContent.innerHTML = createLoadingContent();
    try {
        // const data = JSON.parse(dataText);
        fetch(baseUrl + "api/common/data/incentive/getIncentiveInfo", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'ihealthapi ' + token,
                'Un': un
            },
            body: JSON.stringify({
                phone_data_id: phoneDataId,
            })
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error('网络响应不正常');
                }
                return response.json();
            })
            .then(data => {
                // console.log(11, data.ReturnValue.blood_pressure_data.high_pressure)
                mainContent.innerHTML = createMainContent(data.ReturnValue);  // 创建主要内容
                updatePageData(data.ReturnValue);  // 更新页面数据
                bindEvents(data.ReturnValue);  // 绑定事件
            })
            .catch(error => {
                console.error('获取激励信息失败:', error);
                const err = createErrorContent(CONFIG.text.errorLoadFailed);
                mainContent.innerHTML = '';
                mainContent.appendChild(err);
            });
    } catch (error) {
        console.error('获取激励信息失败:', error);
        const err = createErrorContent(CONFIG.text.errorLoadFailed);
        mainContent.innerHTML = '';
        mainContent.appendChild(err);
    }
}
// 更新页面标题
document.title = CONFIG.text.title;

// DOM加载完成后初始化
document.addEventListener('DOMContentLoaded', initPage);

// 导出函数供全局访问（如需要）
window.BloodPressureApp = {
    CONFIG,
    updatePageData,
    initPage,
    getUrlParams
};
